options:
  formatter: stylish
files:
  include:
      - 'src/main/frontend/scss/**/*.scss'
      - 'src/scss/**/*.scss'
      - 'standalone/main.scss'
  ignore:
    - 'src/main/frontend/scss/components/_text.scss'
rules:
  # Extends
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2

  # Mixins
  mixins-before-declarations: 0

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks: 2
  single-line-per-selector: 2

  # Disallows
  no-color-keywords: 2
  no-color-literals:
    - 2
    -
      allow-rgba: true
  no-css-comments: 2
  no-debug: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 2
  no-ids: 2
  no-important: 2
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-qualifying-elements: 2
  no-trailing-zero: 2
  no-transition-all: 2
  no-url-protocols: 2
  no-vendor-prefixes: 2
  no-warn: 2
  property-units:
    - 2
    -
      global: ['em', 'rem', '%']
      per-property: {font-size: ['rem'], letter-spacing: ['rem','em'], box-shadow: ['px', 'em'], text-shadow: ['px', 'em'], border: ['px', 'em'], border-left: ['px', 'em'], border-right: ['px', 'em'], border-top: ['px', 'em'], border-bottom: ['px', 'em'], border-radius: ['px', 'em', 'rem'], border-width: ['px', 'em'], transition: ['s', 'deg'], min-height: ['em', 'vh'], }

  # Nesting
  force-attribute-nesting: 2
  force-element-nesting: 2
  force-pseudo-nesting: 0

  # Name Formats
  class-name-format:
    -  2
    -
      convention: (^([a-z]*_[a-z]*[-]?[a-z0-9\-]*)(\.[a-z0-9\-]*)?(__[a-z0-9]*[-]?[a-z0-9\-]*)?(--[a-z0-9]*[-]?[a-z0-9\-]*)?(\:[a-z]*)*$)|no-js|js|no-pointer-events|new|no-flexbox|no-flexwrap|flexbox|flexwrap|no-srcset
  function-name-format: 2
  id-name-format: 0
  mixin-name-format: 0
  placeholder-name-format: 2
  variable-name-format: 0

  # Style Guide
  bem-depth: 2
  border-zero: 0
  brace-style: 2
  clean-import-paths: 2
  empty-args: 2
  hex-length:
    - 2
    -
      style: long
  hex-notation: 2
  indentation: 0
  leading-zero: 0
  nesting-depth:
    - 1
    -
      max-depth: 3
  property-sort-order: 0
  quotes: 2
  shorthand-values: 2
  url-quotes: 2
  variable-for-property: 2
  zero-unit: 2

  # Inner Spacing
  space-after-comma: 2
  space-before-colon: 2
  space-after-colon: 2
  space-before-brace: 2
  space-before-bang: 2
  space-after-bang: 2
  space-between-parens: 2
  space-around-operator: 2

  # Final Items
  trailing-semicolon: 2
  final-newline: 0